trigger:
- main

pool:
  name: Default

steps:

- script: |
    docker pull redis
    docker run -d -p 6379:6379 --name myredis redis
  displayName: 'Start Redis'

- script: docker ps
  displayName: 'Verify Redis'

