trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    docker pull redis
    docker run -d -p 6379:6379 --name myredis redis
  displayName: 'Start Redis Container'

- script: |
    docker ps
    sleep 10
    docker logs myredis
  displayName: 'Verify Redis'
